server:
  port: 9090

spring:
  redis:
    host: localhost
    port: 6379
    timeout: 6s
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qwe123456
    resources:
      static-locations: classpath:/templates